#!/bin/bash
#
# Pacchetto installazione per linux di rin2go
# data 		31/03/2021
# autore	MSeverin
#
#########################################################################################
# AGGIORNAMENTO DEL SISTEMA
#########################################################################################
clear
sudo apt-get update && sudo apt-get upgrade

#########################################################################################
# SCARICAMENTO PACCHETTI GIT DI RIN2GO,CSV2GEOJSON,RTKLIB,CRX2RNX
#########################################################################################
clear
git clone https://github.com/mapbox/csv2geojson.git
git clone https://github.com/rtklibexplorer/RTKLIB.git
cd rin2go/other/
wget --no-check-certificate \
'https://drive.google.com/uc?export=download&id=1rnXzvScONL01aMBqQG5ro_zsoUAiCH_M' \
-O CRX2RNX
chmod a+x CRX2RNX

#########################################################################################
# AGGIUNTA DEI PATH
#########################################################################################
export PATH="$PATH:$HOME/bin/rin2go"
export PATH="$PATH:$HOME/bin/rin2go/other"
export PATH="$PATH:$HOME/bin/rin2go/install"

#########################################################################################
# INSTALLAZIONE PACCHETTI TCSH,GIT,PROJ,GDAL,GAWK,GFORTRAN,NPM,CSV2GEOJSON
#########################################################################################
clear
sudo apt-get install tcsh
sudo apt-get install git
sudo apt-get install proj-bin
sudo apt-get install gdal-bin
sudo apt-get install gawk
sudo apt-get install gfortran
sudo apt install npm
sudo npm install -g csv2geojson
sudo apt autoremove

#########################################################################################
# INSTALLAZIONE RTKLIB PACCHETTI CONVBIN,RNX2RTKP
#########################################################################################
clear
rtklibmake

#########################################################################################
# PERMESSI DI ESECUZIONE ALLO SCRIPT
#########################################################################################
#chmod a+x rin2go
